import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pump Calcs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Pump Calcs Landing
        </h1>
      </main>

      <footer>
        <p>©2023 Drew Keat - <a href="www.keatdev.com">KeatDev.com</a></p>
      </footer>
    </div>
  )
}
