import Head from 'next/head'
import Header from "../components/Header"
import ChallengeCard from '../components/ChallengeCard'
import { BottomNavigation, Container, Typography } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pump Calcs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Container component="main" sx={{display: "flex", flexFlow: "column", alignItems: "center"}}>
        <Typography variant="h1" textAlign="center">Pump Calcs Landing</Typography>
        <ChallengeCard style={{margin: "4rem"}}/>
      </Container>

      <BottomNavigation component="footer">
        <p>©2023 Drew Keat - <a href="www.keatdev.com">KeatDev.com</a></p>
      </BottomNavigation >
    </>
  )
}
